### ISSUE TITLE
Shell Script下では、aptではなくapt-getの方がいいかも？

### ISSUE THREAD

**Issue by kkksb** [sankakumusic/vagrant-redmine#2]
**概要**
aptはターミナルで利用
apt-getはシェルスクリプトなどで利用

と、するのが好ましいのかもしれない

**参考**
apt-getとaptの使い分け - Qiita https://qiita.com/piffett/items/a8e3ea4cd6b7bd14f0f0

**Comment by kkksb** [comment]
@sankakumusic 
お時間あるときに、こちらのissueもご覧くださいませ🙇‍♂️

**Comment by sankakumusic** [comment]
@kkksb 
ありがとうございます！これは知りませんでした。
後ほど対応します。
